object Versions {
    const val COMPOSE = "1.1.0-beta01"
    const val LIFECYCLE = "2.3.1"
    const val ACTIVITY = "1.3.1"
    const val JUNIT = "4.13.2"
    const val ANDROID_JUNIT = "1.1.4"
    const val ESPRESSO = "3.5.0"
    const val CODE_QUALITY_TOOLS = "0.22.0"
    const val COMPOSE_NAVIGATION = "2.5.3"
    const val FIREBASE_BOM = "28.4.1"
    const val KOIN = "3.2.0"
    const val OKHTTP = "5.0.0-alpha.2"
    const val MOSHI = "1.8.0"
    const val RETROFIT = "2.9.0"
    const val RX_KOTLIN = "2.2.0"
    const val RX_ANDROID = "2.1.0"
}